import { RANDOM_FIVE_LABEL } from './categoryGenerator.js'

const MAX_RANDOM_FIVE_RETRIES = 5

// The upcoming queue may only ever contain one "Random Five" pack at a time.
// Each queue slot is generated by an independent call with no visibility
// into the other slots, so enforce the cap here by re-rolling a duplicate —
// capped so a small/family-filtered pool where Random Five is the only
// possible pack can't retry forever.
export async function fetchCategoryAvoidingDuplicateRandomFive(fetchCategory, existingQueueLabels) {
  let pack = await fetchCategory()
  let attempts = 0
  while (
    pack.label === RANDOM_FIVE_LABEL &&
    existingQueueLabels.includes(RANDOM_FIVE_LABEL) &&
    attempts < MAX_RANDOM_FIVE_RETRIES
  ) {
    pack = await fetchCategory()
    attempts++
  }
  return pack
}
