const MAX_DUPLICATE_LABEL_RETRIES = 5

// Each queue slot is generated by an independent call with no visibility
// into the other slots' labels, so the same category/combo (e.g. "90s
// Movies", "Random Five") could otherwise land twice in the same queue.
// Re-roll a duplicate — capped so a small/family-filtered pool where very
// few distinct categories are viable can't retry forever.
export async function fetchCategoryAvoidingDuplicateLabel(fetchCategory, existingQueueLabels) {
  let pack = await fetchCategory()
  let attempts = 0
  while (
    existingQueueLabels.includes(pack.label) &&
    attempts < MAX_DUPLICATE_LABEL_RETRIES
  ) {
    pack = await fetchCategory()
    attempts++
  }
  return pack
}
